### PR TITLE
fix memory leak in wasm worker [#21]

### LINKED ISSUE #21: WASM Memory leak
## How to reproduce

This pointer isn't cleaned up: https://github.com/maplibre/font-maker/blob/main/app/public/worker.js#L9

### PR DESCRIPTION
**Pull request by bdon**
Fixes #21 .

Changes proposed in this pull request: balance `malloc` with `free` call

@ChrisLoer

### CODE REVIEW

File: app/public/worker.js [hunk 1]
```diff
@@ -64,6 +67,10 @@ self.onmessage = function (e) {
     ]);
   }
 
+  for (let data_ptr of font_datas) {
+    Module._free(data_ptr);
```
Comment (ChrisLoer) [inline app/public/worker.js:71]: This is a nit, but technically this is is freeing the data before `FT_Done_Face` is called in `free_fontstack`, so maybe a bit more correct to move this down? I don't know of any problem it would cause though.

**Review by ChrisLoer — APPROVED** [review]
I think it would be better to move the font_data free to after `free_fontstack`, but this should already be good enough to prevent the leak.
